# Generated by Django 5.2.11 on 2026-02-17 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=200, verbose_name='Nama Keluarga')),
                ('family_status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Tidak Aktif'), ('DISSOLVED', 'Bubar')], default='ACTIVE', max_length=20, verbose_name='Status Keluarga')),
                ('dissolution_reason', models.CharField(blank=True, help_text='Contoh: Meninggal, Perceraian, Pindah', max_length=100, null=True, verbose_name='Alasan Bubar')),
                ('dissolution_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Bubar')),
                ('address_street', models.CharField(max_length=255, verbose_name='Alamat Jalan')),
                ('address_city', models.CharField(max_length=100, verbose_name='Kota')),
                ('address_province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('address_postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keluarga',
                'verbose_name_plural': 'Keluarga',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Sektor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, help_text='Nomor Induk Jemaat — auto-generate', max_length=15, unique=True, verbose_name='NIJ')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Golongan Darah')),
                ('date_of_birth', models.DateField(verbose_name='Tanggal Lahir')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor HP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Baptis')),
                ('sidi_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Sidi')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Nikah')),
                ('membership_status', models.CharField(choices=[('FULL', 'Anggota Penuh'), ('PREPARATION', 'Anggota Persiapan'), ('TRANSFER_IN', 'Pindah Masuk'), ('TRANSFER_OUT', 'Pindah Keluar')], default='FULL', max_length=20, verbose_name='Status Keanggotaan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('inactive_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alasan Tidak Aktif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/%Y/%m/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.family', verbose_name='Keluarga')),
                ('current_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.sector', verbose_name='Sektor Saat Ini')),
            ],
            options={
                'verbose_name': 'Jemaat',
                'verbose_name_plural': 'Jemaat',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_families', to='members.member', verbose_name='Kepala Keluarga'),
        ),
        migrations.AddField(
            model_name='family',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='members.sector', verbose_name='Sektor'),
        ),
        migrations.CreateModel(
            name='SectorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Tanggal Pindah')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Alasan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh')),
                ('from_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='members.sector', verbose_name='Dari Sektor')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_history', to='members.member', verbose_name='Jemaat')),
                ('to_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='members.sector', verbose_name='Ke Sektor')),
            ],
            options={
                'verbose_name': 'Riwayat Sektor',
                'verbose_name_plural': 'Riwayat Sektor',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='members_mem_member__1c9876_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='members_mem_full_na_3f8d20_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='members_mem_is_acti_65d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_status'], name='members_mem_members_6be344_idx'),
        ),
    ]
