# Generated by Django 5.2.11 on 2026-02-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_family_roles_and_deceased_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='member',
            new_name='members_mem_family__93eb55_idx',
            old_name='members_family_role_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='members_mem_is_dece_8e1bee_idx',
            old_name='members_is_deceased_idx',
        ),
    ]
